clean: true
objc: false
readme: Readme.md
framework_root: MBMessagesSwift
module: MBMessagesSwift
module_version: 0.1
sdk: iphonesimulator

xcodebuild_arguments:
    - "-workspace"
    - "MBMessagesSwift.xcworkspace"
    - "-scheme"
    - "MBMessagesSwift"

author: Mumble
author_url: https://mumbleideas.it/
github_url: https://github.com/Mumble-SRL/MBMessagesSwift

theme: fullwidth

custom_categories:
  - name: MBMessages
    children:
    - MBMessages
    - MBMessagesDelegate
  - name: In App Messages
    children:
    - MBInAppMessage
    - MBInAppMessageStyle
    - MBInAppMessageViewBackgroundStyle
    - MBInAppMessageButton
    - MBInAppMessageButtonLinkType
  - name: Views
    children:
    - MBInAppMessageView
    - MBInAppMessageViewDelegate
    - MBInAppMessageViewStyleDelegate
    - MBInAppMessageTopBannerView
    - MBInAppMessageBottomBannerView
    - MBInAppMessageCenterView
    - MBInAppMessageFullscreenImageView
